site_name: YetAnotherEcommerceSite

markdown_extensions:
  - toc:
      permalink: "#"

theme:
  name: readthedocs

nav:
  - Home: 'index.md'
  - 'API Reference':
    - 'Product': 'api-reference/product.md'