site_name: YetAnotherEcommerceSite

markdown_extensions:
  - toc:
      permalink: "#"

theme:
  name: readthedocs

nav:
  - Home: 'index.md'
  - Schema: 
    - Database: 'schema/database.md'
  - 'API Reference': 
    - Guide: 'api-reference/index.md'
    - Product: 'api-reference/product.md'
    - Auth: 'api-reference/auth.md'
    - User: 'api-reference/user.md'
    - Review: 'api-reference/review.md'
    - Misc: 'api-reference/misc.md'